cache:
  - C:\strawberry -> appveyor.yml
shallow_clone: true
install:
  - if not exist "C:\strawberry" choco install strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Build.PL
  - Build test
