language: perl
os: linux
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.16"
  - "5.14"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  global:
    - builddir=./build-CI
    # try to parse the "perlbrew list" output to get latest perl version
    - stableperl="$(perlbrew list | grep -o '(.*)' | sort | tail -1 | tr -d '()')"
    - RELEASE_TESTING=1
    - AUTOMATED_TESTING=1
    - EXTENDED_TESTING=1
    - AUTHOR_TESTING=1
    # Perl 5.26 won't load modules from inc/ otherwise
    - PERL_USE_UNSAFE_INC=1
    # Moar warnings!!1
    # (Though spews a lot of nonsense for the Perl headers as well.)
    # This also tests that setting CXXFLAGS does not break the compilation
    - CXXFLAGS="-Wall -Wextra"
  matrix:
    - CC=gcc-7 CXX=g++-7
before_install:
  - perlbrew list
  - echo $stableperl
  - "perlbrew exec --with $stableperl cpanm --quiet --notest Dist::Zilla"
  - "perlbrew exec --with $stableperl 'dzil authordeps | grep -v ^inc:: | cpanm --quiet --notest'"
  - "perlbrew exec --with $stableperl dzil build --in $builddir"
install:
  - '(cd $builddir && cpanm --quiet --notest --installdeps --with-configure .)'
script:
  # Check that built dist works
  - '(cd $builddir && perl Build.PL && ./Build && prove -br t)'
  # Check that repo itself works
  - 'perl Build.PL && ./Build && ./Build test'
sudo: false
matrix:
  include:
    # other compilers
    - os: linux
      addons:
        apt:
          sources:
            ubuntu-toolchain-r-test
          packages:
            g++-4.7
      env:
        CC=gcc-4.7 CXX=g++-4.7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5 CXX=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6 CXX=g++-6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
      env:
        - CC=clang-5.0 CXX=clang++-5.0
# vim: sw=2
